### ISSUE TITLE
Syntax highlighting flaws

### ISSUE THREAD

**Issue by jaydenseric** [stephen/vscode-graphql#11]
Several language features don't highlight:

- `"""` documentation blocks
- `scalar`
- `input`

<img width="571" alt="screen shot 2018-01-23 at 6 26 52 pm" src="https://user-images.githubusercontent.com/1754873/35263089-7679d6de-006b-11e8-8506-2777afb25189.png">

**Comment by stephen** [comment]
Can you point me to where the `scalar`/`input` keywords or `"""` style comments are mentioned in the spec? I cannot seem to find them there. http://facebook.github.io/graphql/October2016/#sec-Appendix-Grammar-Summary

**Comment by jaydenseric** [comment]
I don't know where to find it in the latest spec, but they are official features:

* [`Scalar`](http://graphql.org/learn/schema/#scalar-types).
* [`Input`](http://graphql.org/learn/schema/#input-types).
* [`"""`](https://github.com/graphql/graphql-js/pull/927). This has been the official syntax for describing parts of a schema since [`graphql@0.12`](https://github.com/graphql/graphql-js/releases/tag/v0.12.0).

**Comment by stephen** [comment]
Added these in 0.2.2.
