### ISSUE TITLE
Also support graphqlconfig.yml & graphqlconfig.yaml

### ISSUE THREAD

**Issue by schickling** [stephen/vscode-graphql#2]
Would be great if this plugin also would support `graphqlconfig.yml` & `graphqlconfig.yaml` files.

**Comment by stephen** [comment]
Assuming `graphql-config` supports this out of the box, this package doesn't depend on `graphql-config` - [the `graphql-language-service` depends on it](https://github.com/graphql/graphql-language-service/blob/master/packages/graphql-language-service/package.json#L36), so I think we'll want to open an issue there.

That being said, I see that .yml is supported in `graphql-config@1.0.8` - could you verify that this doesn't work for you?

**Comment by schickling** [comment]
Good news! 

![image](https://user-images.githubusercontent.com/1567498/34533376-49a010bc-f0ba-11e7-83b5-395346086ec8.png)

**Comment by schickling** [comment]
So once a new version of `graphql-language-service` is released, would be great to also release a new version of `vscode-graphql` :)

**Comment by stephen** [comment]
sgtm! which slack is that? :)

**Comment by schickling** [comment]
GraphQL + Graphcool

**Comment by stephen** [comment]
I believe this should be fixed in 0.1.5.

**Comment by schickling** [comment]
At least I don't see any effect. Maybe you can try to clone [this repo](https://github.com/graphcool/graphcool-server-example) and see whether "Go to definition" works for you on a SDL level.

**Comment by stephen** [comment]
I think this is an issue with the language service not supporting the SDL very well yet, but `.yml` configurations themselves should work now. See: https://github.com/graphql/graphql-language-service/issues/85

I am going to close this for now since there is no change to make in this repo.
