### ISSUE TITLE
Starting client failed

### ISSUE THREAD

**Issue by samuelcastro** [stephen/vscode-graphql#27]
I'm having this issue when starting it.

<img width="640" alt="Screen Shot 2020-05-22 at 5 50 02 PM" src="https://user-images.githubusercontent.com/5281701/82718012-bc62d100-9c54-11ea-87e7-a9969a683687.png">

Any idea?

**Comment by samuelcastro** [comment]
So no answers, I'm assuming that this project is not maintained anymore, if that's the case let us me know asap, I'll notify the `graphql-config` about it and remove the reference of this project on it.

**Comment by stephen** [comment]
this is fixed in 0.3.0.
